Profile page
matzapata/PG-Henry pull request #43
Opened 2022-08-23 20:04 UTC by Xxmbxxmb

Componente generico para subir imagenes listo, me falta crear la ruta en el back para que se agregue a la base de datos.
Formulario para editar perfil listo, me falta hacer la logica para poder editar solamente el perfil propio.

2022-08-23 20:37 UTC, matzapata commented on api/src/routes/users.ts
> +  async (req: express.Request, res: express.Response) => {
Habria que agregar el middleware de auth para que solo los usuarios loggeados puedan cambiar su contraseña. El middleware se llama isProtected().

2022-08-23 20:38 UTC, matzapata commented on api/src/routes/users.ts
> +      return res.status(400).send("Faltan parametros requeridos!");
El email se deberia sacar del JWT que viene con la autenticacion, para que el usuario unicamente pueda alterar su contraseña y la de nadie mas.

2022-08-23 20:40 UTC, matzapata commented on client/src/components/UploadFile.tsx
> +      await fetch("https://api.cloudinary.com/v1_1/drgqlk8l3/image/upload", {
Estaria bueno dejarlo como variable de entorno por si en un futuro hay que cambiarla

2022-08-23 20:40 UTC, matzapata commented on client/src/components/UploadFile.tsx
> +          upload_preset: "unqyzvup",
lo mismo aca respecto a variable de entorno

2022-08-23 20:40 UTC, matzapata commented on client/src/components/UploadFile.tsx
> +                />
Se podria usar Chakra

2022-08-23 20:41 UTC, matzapata commented on client/src/components/UploadFile.tsx
> +      )} */}
Eliminar?

2022-08-23 20:41 UTC, matzapata commented on client/src/pages/Perfil.tsx
> +                  {/* <Button w="full">Cambiar Imagen</Button> */}
Eliminar?

2022-08-23 20:42 UTC, Xxmbxxmb commented on api/src/routes/users.ts
> +  async (req: express.Request, res: express.Response) => {
un crack mati! lo arreglo y lo subo bien

2022-08-23 20:43 UTC, matzapata commented on client/src/redux/slices/perfilSlices.ts
> +);
El slice no tiene un estado...
El nombre de la accion es el del reducer y el de la accion. Ejemplo: `perfil/changePassword` siendo que el slice es registrado en `store.ts` como `perfil`

2022-08-23 20:44 UTC, matzapata requested changes
Fundamental lo de proteger la ruta de cambio de contraseña, el resto en gral son detalles.

2022-08-23 20:50 UTC, Xxmbxxmb commented on client/src/pages/Perfil.tsx
> +                  {/* <Button w="full">Cambiar Imagen</Button> */}
aqui lo de funcion y titulo son props que se le pasan al componente generico, para que tengan distintos titulos en el header y boton que se apreta

el comentario de abajo si se me fue borrarlo

2022-08-24 18:53 UTC, deca38 approved these changes

2022-08-24 19:07 UTC, matzapata approved these changes

2022-08-24 19:07 UTC, merged